# Generated by Django 3.2.12 on 2022-05-28 06:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
