# Generated by Django 3.2.12 on 2022-05-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exam_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='body',
            new_name='content',
        ),
    ]
