# Generated by Django 3.2.12 on 2022-05-28 06:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_exam_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
