# Generated by Django 3.2.12 on 2022-05-28 06:49

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_exam_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
