# Generated by Django 3.2.12 on 2022-05-28 10:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220528_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='tiny',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
