# Generated by Django 3.2.12 on 2022-05-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_exam_tiny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='content',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='tiny',
        ),
    ]
