# Generated by Django 3.2.12 on 2022-05-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220528_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='text',
            new_name='content',
        ),
    ]
