# Generated by Django 3.2.12 on 2022-05-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220531_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='status',
            field=models.IntegerField(choices=[(0, 'LOADING...'), (1, 'UPDATED')], default=0),
        ),
    ]
