# Generated by Django 3.2.12 on 2022-05-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_exam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('loading', 'LOADING...'), ('updated', 'UPDATED')], default='loading', max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='status',
            field=models.CharField(choices=[('loading', 'LOADING...'), ('updated', 'UPDATED')], default='loading', max_length=10),
        ),
    ]
