# Generated by Django 3.2.12 on 2022-05-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220531_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('LOADING...', 'loading'), ('UPDATED', 'updated')], default='loading', max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='status',
            field=models.CharField(choices=[('LOADING...', 'loading'), ('UPDATED', 'updated')], default='loading', max_length=10),
        ),
    ]
