# Generated by Django 3.2.12 on 2022-05-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220531_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
