# Generated by Django 3.2.12 on 2022-08-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_examnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examnews',
            old_name='content',
            new_name='contents',
        ),
        migrations.AlterField(
            model_name='examnews',
            name='exam_type',
            field=models.CharField(choices=[('neco', 'neco'), ('waec', 'waec'), ('jupeb', 'jupeb'), ('nabteb', 'nabteb')], default='', max_length=10),
        ),
    ]
